# Generated by Django 6.1 on 2026-08-13 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='experiences.experiencesession')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('is_sms_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
