# Generated by Django 6.0.5 on 2026-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencesession',
            name='link_received',
            field=models.BooleanField(default=False),
        ),
    ]
