# Generated by Django 6.1 on 2026-08-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='backgrounds/')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('overlay_image', models.ImageField(upload_to='products/overlays/')),
                ('season', models.CharField(default='26 SS', max_length=20)),
                ('gender', models.CharField(choices=[('FEMALE', '여성'), ('MALE', '남성'), ('UNISEX', '공용')], default='FEMALE', max_length=10)),
                ('category', models.CharField(default='숄더백', max_length=50)),
                ('like_count', models.IntegerField(default=0)),
            ],
        ),
    ]
