# Generated by Django 6.1 on 2026-08-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
