# Generated by Django 6.0.5 on 2026-08-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_background_tags_product_color_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='season',
        ),
        migrations.AlterField(
            model_name='background',
            name='type',
            field=models.CharField(choices=[('나라 별', '나라 별'), ('큐레이션룸', '큐레이션룸')], default='나라 별', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('토트백&쇼퍼백', '토트백&쇼퍼백'), ('숄더백&크로스백', '숄더백&크로스백'), ('백팩', '백팩'), ('탑 핸들백', '탑 핸들백'), ('트래블', '트래블'), ('벨트백', '벨트백'), ('미니백', '미니백'), ('클러치&파우치', '클러치&파우치')], default='숄더백&크로스백', max_length=50),
        ),
    ]
