# Generated by Django 6.0.5 on 2026-08-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_background_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='choose_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='choose_count',
            field=models.IntegerField(default=0),
        ),
    ]
