# Generated by Django 6.0.5 on 2026-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_background_choose_count_product_choose_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='link_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
