# Generated by Django 6.0.5 on 2026-08-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_background_link_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='link_count',
        ),
        migrations.AddField(
            model_name='product',
            name='link_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
