# Generated by Django 6.0.5 on 2026-08-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_background_link_count_product_link_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='today_like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='today_like_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='today_link_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='today_link_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
