# Generated by Django 6.0.5 on 2026-08-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_today_like_count_product_today_like_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='today_link_count',
            field=models.IntegerField(default=0),
        ),
    ]
