# Generated by Django 6.0.5 on 2026-08-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_choose_count_alter_product_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='choose_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
