# Generated by Django 6.1 on 2026-08-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_background_choose_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='today_choose_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='today_choose_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
