# Generated by Django 6.1 on 2026-08-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_today_choose_count_product_today_choose_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='today_choose_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='background',
            name='today_choose_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
