# Generated by Django 6.0.5 on 2026-08-20 23:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_background_today_choose_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('choose_count', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'date')},
            },
        ),
    ]
